version: "3"
services:
    core:
        build:
            context: ../../core
            dockerfile: Dockerfile.local
        env_file:
            - ../../core/env_variables/env
        volumes:
            - ../../core:/usr/src/librejournal
        depends_on:
            - core_db
        ports:
            - 9001:5000
        command: bash start_local.sh


    core_db:
        build:
            context: .
            dockerfile: db_dockerfile
        env_file:
            - ./db
        ports:
            - 5433:5432
        volumes:
            - core_db:/var/lib/postgresql/data

    rabbitmq:
        hostname: rabbit
        image: rabbitmq:latest
        env_file:
        - env_rabbitmq

    redis:
        image: redis:latest
        ports:
            - 6379:6379

    celery_worker:
        restart: always
        build:
            context: ../../core
            dockerfile: Dockerfile.worker
        volumes:
            - ../../core:/usr/src/librejournal/core
        env_file:
            - ../../core/env_variables/env
        depends_on:
            - core_db
            - core
            - redis
            - rabbitmq

volumes:
    core_db: